#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Asistanı_v1._0
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProjeYönetimiX")]
	public partial class ___00ProjeAsistanıDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertÜcretlendirme(Ücretlendirme instance);
    partial void UpdateÜcretlendirme(Ücretlendirme instance);
    partial void DeleteÜcretlendirme(Ücretlendirme instance);
    partial void InsertYetenekBilgisi(YetenekBilgisi instance);
    partial void UpdateYetenekBilgisi(YetenekBilgisi instance);
    partial void DeleteYetenekBilgisi(YetenekBilgisi instance);
    partial void InsertPersonelBilgisi(PersonelBilgisi instance);
    partial void UpdatePersonelBilgisi(PersonelBilgisi instance);
    partial void DeletePersonelBilgisi(PersonelBilgisi instance);
    partial void InsertYoneticiBilgisi(YoneticiBilgisi instance);
    partial void UpdateYoneticiBilgisi(YoneticiBilgisi instance);
    partial void DeleteYoneticiBilgisi(YoneticiBilgisi instance);
    partial void InsertProjeBilgi(ProjeBilgi instance);
    partial void UpdateProjeBilgi(ProjeBilgi instance);
    partial void DeleteProjeBilgi(ProjeBilgi instance);
    #endregion
		
		public ___00ProjeAsistanıDataContext() : 
				base(global::Proje_Asistanı_v1._0.Properties.Settings.Default.ProjeYönetimiXConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ___00ProjeAsistanıDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ___00ProjeAsistanıDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ___00ProjeAsistanıDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ___00ProjeAsistanıDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ücretlendirme> Ücretlendirmes
		{
			get
			{
				return this.GetTable<Ücretlendirme>();
			}
		}
		
		public System.Data.Linq.Table<YetenekBilgisi> YetenekBilgisis
		{
			get
			{
				return this.GetTable<YetenekBilgisi>();
			}
		}
		
		public System.Data.Linq.Table<PersonelBilgisi> PersonelBilgisis
		{
			get
			{
				return this.GetTable<PersonelBilgisi>();
			}
		}
		
		public System.Data.Linq.Table<YoneticiBilgisi> YoneticiBilgisis
		{
			get
			{
				return this.GetTable<YoneticiBilgisi>();
			}
		}
		
		public System.Data.Linq.Table<PersonelYetenek> PersonelYeteneks
		{
			get
			{
				return this.GetTable<PersonelYetenek>();
			}
		}
		
		public System.Data.Linq.Table<ProjeBilgi> ProjeBilgis
		{
			get
			{
				return this.GetTable<ProjeBilgi>();
			}
		}
		
		public System.Data.Linq.Table<ProjeDetay> ProjeDetays
		{
			get
			{
				return this.GetTable<ProjeDetay>();
			}
		}
		
		public System.Data.Linq.Table<ProjeDurumu> ProjeDurumus
		{
			get
			{
				return this.GetTable<ProjeDurumu>();
			}
		}
		
		public System.Data.Linq.Table<ProjeGörevDağılımı> ProjeGörevDağılımıs
		{
			get
			{
				return this.GetTable<ProjeGörevDağılımı>();
			}
		}
		
		public System.Data.Linq.Table<ProjeUstaAtaması> ProjeUstaAtamasıs
		{
			get
			{
				return this.GetTable<ProjeUstaAtaması>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ÜcretlendirmeData")]
		public ISingleResult<ÜcretlendirmeDataResult> ÜcretlendirmeData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ÜcretlendirmeDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AtanacakProje")]
		public ISingleResult<SP_AtanacakProjeResult> SP_AtanacakProje()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_AtanacakProjeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EnDüşükTarih")]
		public ISingleResult<SP_EnDüşükTarihResult> SP_EnDüşükTarih()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_EnDüşükTarihResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EnYüksekTarih")]
		public ISingleResult<SP_EnYüksekTarihResult> SP_EnYüksekTarih()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_EnYüksekTarihResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Giris")]
		public int SP_Giris([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adi", DbType="NVarChar(50)")] string adi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sifre", DbType="NVarChar(50)")] string sifre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deger", DbType="NVarChar(2)")] ref string deger)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adi, sifre, deger);
			deger = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GörevDağılımıEkle")]
		public int SP_GörevDağılımıEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNumarası", DbType="Int")] System.Nullable<int> personelNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Görevİsmi", DbType="Int")] System.Nullable<int> görevİsmi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevBaşlangıç", DbType="Date")] System.Nullable<System.DateTime> görevBaşlangıç, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevBitiş", DbType="Date")] System.Nullable<System.DateTime> görevBitiş, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ücret", DbType="Int")] System.Nullable<int> ücret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, personelNumarası, görevİsmi, görevBaşlangıç, görevBitiş, ücret);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GörevDağılımıGetir")]
		public ISingleResult<SP_GörevDağılımıGetirResult> SP_GörevDağılımıGetir()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_GörevDağılımıGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GörevDağılımıProjeBazlı")]
		public int SP_GörevDağılımıProjeBazlı([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ücret", DbType="NVarChar(10)")] ref string ücret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, ücret);
			ücret = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GörevDağılımıProjeBazlıTümVeri")]
		public ISingleResult<SP_GörevDağılımıProjeBazlıTümVeriResult> SP_GörevDağılımıProjeBazlıTümVeri([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası);
			return ((ISingleResult<SP_GörevDağılımıProjeBazlıTümVeriResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_IsciTürüNo")]
		public int SP_IsciTürüNo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string İşçiStatü, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÜcretNumarasi", DbType="NVarChar(3)")] ref string ücretNumarasi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), İşçiStatü, ücretNumarasi);
			ücretNumarasi = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OlumluİşçiSayısı")]
		public int SP_OlumluİşçiSayısı([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YetenekNumarası", DbType="Int")] System.Nullable<int> yetenekNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(3)")] ref string İşçiSayısı)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yetenekNumarası, İşçiSayısı);
			İşçiSayısı = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelBilgisiEkle")]
		public int SP_PersonelBilgisiEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNumarası", DbType="Int")] System.Nullable<int> personelNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adi", DbType="NVarChar(50)")] string adi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Soyadi", DbType="NVarChar(50)")] string soyadi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÜcretNumarası", DbType="Int")] System.Nullable<int> ücretNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Durum", DbType="Int")] System.Nullable<int> durum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> İşBaşlangıç, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> işBitiş, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Yorgunluk", DbType="Int")] System.Nullable<int> yorgunluk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNumarası, adi, soyadi, ücretNumarası, durum, İşBaşlangıç, işBitiş, yorgunluk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelDurumGüncelle")]
		public int SP_PersonelDurumGüncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNumarası", DbType="Int")] System.Nullable<int> personelNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> İşBaşlangıç, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> İşBitiş)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNumarası, İşBaşlangıç, İşBitiş);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelDurumGüncelle2")]
		public int SP_PersonelDurumGüncelle2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="NVarChar(7)")] string personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelYetenekEkle")]
		public int SP_PersonelYetenekEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="Int")] System.Nullable<int> personelNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YetenekNo", DbType="Int")] System.Nullable<int> yetenekNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo, yetenekNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeBilgisiEkle")]
		public int SP_ProjeBilgisiEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeAdi", DbType="NVarChar(250)")] string projeAdi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeBaslangic", DbType="Date")] System.Nullable<System.DateTime> projeBaslangic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeBitis", DbType="Date")] System.Nullable<System.DateTime> projeBitis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeDurum", DbType="Int")] System.Nullable<int> projeDurum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeGün", DbType="Int")] System.Nullable<int> projeGün)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, projeAdi, projeBaslangic, projeBitis, projeDurum, projeGün);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeDetayData")]
		public ISingleResult<SP_ProjeDetayDataResult> SP_ProjeDetayData([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası);
			return ((ISingleResult<SP_ProjeDetayDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeDetayEkle")]
		public int SP_ProjeDetayEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevIsmi", DbType="Int")] System.Nullable<int> görevIsmi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevSüresi", DbType="Int")] System.Nullable<int> görevSüresi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsciSayisi", DbType="Int")] System.Nullable<int> isciSayisi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevBaslangic", DbType="Date")] System.Nullable<System.DateTime> görevBaslangic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevBitis", DbType="Date")] System.Nullable<System.DateTime> görevBitis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevDurumu", DbType="Int")] System.Nullable<int> görevDurumu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, görevIsmi, görevSüresi, isciSayisi, görevBaslangic, görevBitis, görevDurumu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeDurumuEkle")]
		public int SP_ProjeDurumuEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeDurumu", DbType="Int")] System.Nullable<int> projeDurumu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, projeDurumu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeGünSayısı")]
		public int SP_ProjeGünSayısı([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GünSayısı", DbType="Int")] ref System.Nullable<int> günSayısı)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, günSayısı);
			günSayısı = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeİşçiToplamÜcret")]
		public int SP_ProjeİşçiToplamÜcret([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ücret1", DbType="NVarChar(10)")] ref string ücret1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, ücret1);
			ücret1 = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeSeç")]
		public int SP_ProjeSeç()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeUstaAta")]
		public int SP_ProjeUstaAta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNumarası", DbType="Int")] System.Nullable<int> personelNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÇalışmaGünü", DbType="Int")] System.Nullable<int> çalışmaGünü, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToplamÜcret", DbType="Int")] System.Nullable<int> toplamÜcret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, personelNumarası, çalışmaGünü, toplamÜcret);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeUstaToplamÜcret")]
		public int SP_ProjeUstaToplamÜcret([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ücret1", DbType="NVarChar(10)")] ref string ücret1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, ücret1);
			ücret1 = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Temizle")]
		public int SP_Temizle()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ÜcretlendirmeData")]
		public ISingleResult<SP_ÜcretlendirmeDataResult> SP_ÜcretlendirmeData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ÜcretlendirmeDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_YetenekData")]
		public ISingleResult<SP_YetenekDataResult> SP_YetenekData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_YetenekDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_YetenekNoGetir")]
		public int SP_YetenekNoGetir([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YetenekAdi", DbType="NVarChar(250)")] string yetenekAdi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YetenekNo", DbType="NVarChar(3)")] ref string yetenekNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yetenekAdi, yetenekNo);
			yetenekNo = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_YoneticiBilgisi")]
		public int SP_YoneticiBilgisi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adi", DbType="NVarChar(50)")] string adi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="NVarChar(50)")] ref string personelNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adi2", DbType="NVarChar(50)")] ref string adi2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Authority", DbType="NVarChar(2)")] ref string authority, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Picture", DbType="NVarChar(250)")] ref string picture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adi, password, personelNo, adi2, authority, picture);
			personelNo = ((string)(result.GetParameterValue(2)));
			adi2 = ((string)(result.GetParameterValue(3)));
			authority = ((string)(result.GetParameterValue(4)));
			picture = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeSayısı")]
		public int SP_ProjeSayısı([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count", DbType="NVarChar(3)")] ref string count, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count2", DbType="NVarChar(3)")] ref string count2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count3", DbType="NVarChar(3)")] ref string count3)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), count, count2, count3);
			count = ((string)(result.GetParameterValue(0)));
			count2 = ((string)(result.GetParameterValue(1)));
			count3 = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelYetenekGetir")]
		public ISingleResult<SP_PersonelYetenekGetirResult> SP_PersonelYetenekGetir([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="Int")] System.Nullable<int> personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo);
			return ((ISingleResult<SP_PersonelYetenekGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelYetenekSil")]
		public int SP_PersonelYetenekSil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="Int")] System.Nullable<int> personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelBilgisiGüncelle")]
		public int SP_PersonelBilgisiGüncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNumarası", DbType="Int")] System.Nullable<int> personelNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adi", DbType="NVarChar(50)")] string adi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Soyadi", DbType="NVarChar(50)")] string soyadi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÜcretNumarası", DbType="Int")] System.Nullable<int> ücretNumarası)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNumarası, adi, soyadi, ücretNumarası);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelSil")]
		public int SP_PersonelSil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="Int")] System.Nullable<int> personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelBilgisi")]
		public ISingleResult<SP_PersonelBilgisiResult> SP_PersonelBilgisi()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_PersonelBilgisiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ÜcretBilgisiGetir")]
		public ISingleResult<SP_ÜcretBilgisiGetirResult> SP_ÜcretBilgisiGetir()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ÜcretBilgisiGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ÜcretBirimiEkle")]
		public int SP_ÜcretBirimiEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÜcretNo", DbType="Int")] System.Nullable<int> ücretNo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string İşçiStatü, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ücret", DbType="Int")] System.Nullable<int> ücret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ücretNo, İşçiStatü, ücret);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ÜcretBirimiGüncelle")]
		public int SP_ÜcretBirimiGüncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÜcretNo", DbType="Int")] System.Nullable<int> ücretNo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string İşçiStatü, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ücret", DbType="Int")] System.Nullable<int> ücret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ücretNo, İşçiStatü, ücret);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ÜcretBirimiSil")]
		public int SP_ÜcretBirimiSil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ÜcretNo", DbType="Int")] System.Nullable<int> ücretNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ücretNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeBilgiGüncelle")]
		public int SP_ProjeBilgiGüncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeAdi", DbType="NVarChar(250)")] string projeAdi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeBaslangic", DbType="Date")] System.Nullable<System.DateTime> projeBaslangic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeBitis", DbType="Date")] System.Nullable<System.DateTime> projeBitis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeGün", DbType="Int")] System.Nullable<int> projeGün)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, projeAdi, projeBaslangic, projeBitis, projeGün);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeBilgiSil")]
		public int SP_ProjeBilgiSil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNo", DbType="Int")] System.Nullable<int> projeNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeBilgiGetir")]
		public ISingleResult<SP_ProjeBilgiGetirResult> SP_ProjeBilgiGetir()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ProjeBilgiGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeDetayGüncelle")]
		public int SP_ProjeDetayGüncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNumarası", DbType="Int")] System.Nullable<int> projeNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevIsmi", DbType="Int")] System.Nullable<int> görevIsmi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevSüresi", DbType="Int")] System.Nullable<int> görevSüresi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsciSayisi", DbType="Int")] System.Nullable<int> isciSayisi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevBaslangic", DbType="Date")] System.Nullable<System.DateTime> görevBaslangic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevBitis", DbType="Date")] System.Nullable<System.DateTime> görevBitis)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNumarası, görevIsmi, görevSüresi, isciSayisi, görevBaslangic, görevBitis);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeDetaySil")]
		public int SP_ProjeDetaySil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNo", DbType="Int")] System.Nullable<int> projeNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Görevİsmi", DbType="Int")] System.Nullable<int> görevİsmi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNo, görevİsmi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeBilgiŞart")]
		public ISingleResult<SP_ProjeBilgiŞartResult> SP_ProjeBilgiŞart([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNum", DbType="NVarChar(2)")] string projeNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNum);
			return ((ISingleResult<SP_ProjeBilgiŞartResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AtanacakGörevler")]
		public ISingleResult<SP_AtanacakGörevlerResult> SP_AtanacakGörevler([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNo", DbType="NVarChar(2)")] string projeNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNo);
			return ((ISingleResult<SP_AtanacakGörevlerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AtanacakProjeGün")]
		public ISingleResult<SP_AtanacakProjeGünResult> SP_AtanacakProjeGün([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNum", DbType="NVarChar(2)")] string projeNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNum);
			return ((ISingleResult<SP_AtanacakProjeGünResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ProjeUstaGöster")]
		public ISingleResult<SP_ProjeUstaGösterResult> SP_ProjeUstaGöster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProjeNum", DbType="NVarChar(2)")] string projeNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), projeNum);
			return ((ISingleResult<SP_ProjeUstaGösterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MüsaitFirmaİşçisi")]
		public ISingleResult<SP_MüsaitFirmaİşçisiResult> SP_MüsaitFirmaİşçisi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevNumarası", DbType="Int")] System.Nullable<int> görevNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="NVarChar(2)")] string personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), görevNumarası, personelNo);
			return ((ISingleResult<SP_MüsaitFirmaİşçisiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MüsaitFirmaUstaları")]
		public ISingleResult<SP_MüsaitFirmaUstalarıResult> SP_MüsaitFirmaUstaları([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="NVarChar(2)")] string personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo);
			return ((ISingleResult<SP_MüsaitFirmaUstalarıResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MüsaitTaşeronİşçisi")]
		public ISingleResult<SP_MüsaitTaşeronİşçisiResult> SP_MüsaitTaşeronİşçisi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GörevNumarası", DbType="Int")] System.Nullable<int> görevNumarası, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="NVarChar(2)")] string personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), görevNumarası, personelNo);
			return ((ISingleResult<SP_MüsaitTaşeronİşçisiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MüsaitTaşeronUstaları")]
		public ISingleResult<SP_MüsaitTaşeronUstalarıResult> SP_MüsaitTaşeronUstaları([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="NVarChar(2)")] string personelNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo);
			return ((ISingleResult<SP_MüsaitTaşeronUstalarıResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PersonelDurumuX")]
		public ISingleResult<SP_PersonelDurumuXResult> SP_PersonelDurumuX([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonelNo", DbType="Int")] System.Nullable<int> personelNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tarih", DbType="Date")] System.Nullable<System.DateTime> tarih)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personelNo, tarih);
			return ((ISingleResult<SP_PersonelDurumuXResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Deneme")]
		public int Deneme()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ücretlendirme")]
	public partial class Ücretlendirme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ÜcretNumarasi;
		
		private string _İşçiStatü;
		
		private System.Nullable<int> _Ücret;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnÜcretNumarasiChanging(int value);
    partial void OnÜcretNumarasiChanged();
    partial void OnİşçiStatüChanging(string value);
    partial void OnİşçiStatüChanged();
    partial void OnÜcretChanging(System.Nullable<int> value);
    partial void OnÜcretChanged();
    #endregion
		
		public Ücretlendirme()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜcretNumarasi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ÜcretNumarasi
		{
			get
			{
				return this._ÜcretNumarasi;
			}
			set
			{
				if ((this._ÜcretNumarasi != value))
				{
					this.OnÜcretNumarasiChanging(value);
					this.SendPropertyChanging();
					this._ÜcretNumarasi = value;
					this.SendPropertyChanged("ÜcretNumarasi");
					this.OnÜcretNumarasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşçiStatü", DbType="NVarChar(250)")]
		public string İşçiStatü
		{
			get
			{
				return this._İşçiStatü;
			}
			set
			{
				if ((this._İşçiStatü != value))
				{
					this.OnİşçiStatüChanging(value);
					this.SendPropertyChanging();
					this._İşçiStatü = value;
					this.SendPropertyChanged("İşçiStatü");
					this.OnİşçiStatüChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this.OnÜcretChanging(value);
					this.SendPropertyChanging();
					this._Ücret = value;
					this.SendPropertyChanged("Ücret");
					this.OnÜcretChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YetenekBilgisi")]
	public partial class YetenekBilgisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YetenekNumarasi;
		
		private string _YetenekAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYetenekNumarasiChanging(int value);
    partial void OnYetenekNumarasiChanged();
    partial void OnYetenekAdiChanging(string value);
    partial void OnYetenekAdiChanged();
    #endregion
		
		public YetenekBilgisi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetenekNumarasi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int YetenekNumarasi
		{
			get
			{
				return this._YetenekNumarasi;
			}
			set
			{
				if ((this._YetenekNumarasi != value))
				{
					this.OnYetenekNumarasiChanging(value);
					this.SendPropertyChanging();
					this._YetenekNumarasi = value;
					this.SendPropertyChanged("YetenekNumarasi");
					this.OnYetenekNumarasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetenekAdi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string YetenekAdi
		{
			get
			{
				return this._YetenekAdi;
			}
			set
			{
				if ((this._YetenekAdi != value))
				{
					this.OnYetenekAdiChanging(value);
					this.SendPropertyChanging();
					this._YetenekAdi = value;
					this.SendPropertyChanged("YetenekAdi");
					this.OnYetenekAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonelBilgisi")]
	public partial class PersonelBilgisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonelNumarası;
		
		private string _Adi;
		
		private string _Soyadi;
		
		private int _ÜcretNumarasi;
		
		private System.Nullable<int> _Durum;
		
		private System.Nullable<System.DateTime> _İsBaslangic;
		
		private System.Nullable<System.DateTime> _İsBitis;
		
		private System.Nullable<double> _YorgunlukPayi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonelNumarasıChanging(int value);
    partial void OnPersonelNumarasıChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSoyadiChanging(string value);
    partial void OnSoyadiChanged();
    partial void OnÜcretNumarasiChanging(int value);
    partial void OnÜcretNumarasiChanged();
    partial void OnDurumChanging(System.Nullable<int> value);
    partial void OnDurumChanged();
    partial void OnİsBaslangicChanging(System.Nullable<System.DateTime> value);
    partial void OnİsBaslangicChanged();
    partial void OnİsBitisChanging(System.Nullable<System.DateTime> value);
    partial void OnİsBitisChanged();
    partial void OnYorgunlukPayiChanging(System.Nullable<double> value);
    partial void OnYorgunlukPayiChanged();
    #endregion
		
		public PersonelBilgisi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this.OnPersonelNumarasıChanging(value);
					this.SendPropertyChanging();
					this._PersonelNumarası = value;
					this.SendPropertyChanged("PersonelNumarası");
					this.OnPersonelNumarasıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this.OnSoyadiChanging(value);
					this.SendPropertyChanging();
					this._Soyadi = value;
					this.SendPropertyChanged("Soyadi");
					this.OnSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜcretNumarasi", DbType="Int NOT NULL")]
		public int ÜcretNumarasi
		{
			get
			{
				return this._ÜcretNumarasi;
			}
			set
			{
				if ((this._ÜcretNumarasi != value))
				{
					this.OnÜcretNumarasiChanging(value);
					this.SendPropertyChanging();
					this._ÜcretNumarasi = value;
					this.SendPropertyChanged("ÜcretNumarasi");
					this.OnÜcretNumarasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="Int")]
		public System.Nullable<int> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İsBaslangic", DbType="Date")]
		public System.Nullable<System.DateTime> İsBaslangic
		{
			get
			{
				return this._İsBaslangic;
			}
			set
			{
				if ((this._İsBaslangic != value))
				{
					this.OnİsBaslangicChanging(value);
					this.SendPropertyChanging();
					this._İsBaslangic = value;
					this.SendPropertyChanged("İsBaslangic");
					this.OnİsBaslangicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İsBitis", DbType="Date")]
		public System.Nullable<System.DateTime> İsBitis
		{
			get
			{
				return this._İsBitis;
			}
			set
			{
				if ((this._İsBitis != value))
				{
					this.OnİsBitisChanging(value);
					this.SendPropertyChanging();
					this._İsBitis = value;
					this.SendPropertyChanged("İsBitis");
					this.OnİsBitisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorgunlukPayi", DbType="Float")]
		public System.Nullable<double> YorgunlukPayi
		{
			get
			{
				return this._YorgunlukPayi;
			}
			set
			{
				if ((this._YorgunlukPayi != value))
				{
					this.OnYorgunlukPayiChanging(value);
					this.SendPropertyChanging();
					this._YorgunlukPayi = value;
					this.SendPropertyChanged("YorgunlukPayi");
					this.OnYorgunlukPayiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YoneticiBilgisi")]
	public partial class YoneticiBilgisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PERSONEL_ID;
		
		private string _NAME;
		
		private string _PASSWORD;
		
		private int _AUTHORITY;
		
		private string _PICTURE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPERSONEL_IDChanging(int value);
    partial void OnPERSONEL_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnAUTHORITYChanging(int value);
    partial void OnAUTHORITYChanged();
    partial void OnPICTUREChanging(string value);
    partial void OnPICTUREChanged();
    #endregion
		
		public YoneticiBilgisi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSONEL_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PERSONEL_ID
		{
			get
			{
				return this._PERSONEL_ID;
			}
			set
			{
				if ((this._PERSONEL_ID != value))
				{
					this.OnPERSONEL_IDChanging(value);
					this.SendPropertyChanging();
					this._PERSONEL_ID = value;
					this.SendPropertyChanged("PERSONEL_ID");
					this.OnPERSONEL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHORITY", DbType="Int NOT NULL")]
		public int AUTHORITY
		{
			get
			{
				return this._AUTHORITY;
			}
			set
			{
				if ((this._AUTHORITY != value))
				{
					this.OnAUTHORITYChanging(value);
					this.SendPropertyChanging();
					this._AUTHORITY = value;
					this.SendPropertyChanged("AUTHORITY");
					this.OnAUTHORITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICTURE", DbType="NVarChar(250)")]
		public string PICTURE
		{
			get
			{
				return this._PICTURE;
			}
			set
			{
				if ((this._PICTURE != value))
				{
					this.OnPICTUREChanging(value);
					this.SendPropertyChanging();
					this._PICTURE = value;
					this.SendPropertyChanged("PICTURE");
					this.OnPICTUREChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonelYetenek")]
	public partial class PersonelYetenek
	{
		
		private System.Nullable<int> _PersonelNumarasi;
		
		private System.Nullable<int> _YetenekNumarasi;
		
		public PersonelYetenek()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarasi", DbType="Int")]
		public System.Nullable<int> PersonelNumarasi
		{
			get
			{
				return this._PersonelNumarasi;
			}
			set
			{
				if ((this._PersonelNumarasi != value))
				{
					this._PersonelNumarasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetenekNumarasi", DbType="Int")]
		public System.Nullable<int> YetenekNumarasi
		{
			get
			{
				return this._YetenekNumarasi;
			}
			set
			{
				if ((this._YetenekNumarasi != value))
				{
					this._YetenekNumarasi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjeBilgi")]
	public partial class ProjeBilgi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProjeNumarasıChanging(int value);
    partial void OnProjeNumarasıChanged();
    partial void OnProjeAdıChanging(string value);
    partial void OnProjeAdıChanged();
    partial void OnProjeBaşlangıçTarihiChanging(System.DateTime value);
    partial void OnProjeBaşlangıçTarihiChanged();
    partial void OnProjeBitişTarihiChanging(System.DateTime value);
    partial void OnProjeBitişTarihiChanged();
    partial void OnProjeDurumuChanging(System.Nullable<int> value);
    partial void OnProjeDurumuChanged();
    partial void OnProjeGünChanging(System.Nullable<int> value);
    partial void OnProjeGünChanged();
    #endregion
		
		public ProjeBilgi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this.OnProjeNumarasıChanging(value);
					this.SendPropertyChanging();
					this._ProjeNumarası = value;
					this.SendPropertyChanged("ProjeNumarası");
					this.OnProjeNumarasıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this.OnProjeAdıChanging(value);
					this.SendPropertyChanging();
					this._ProjeAdı = value;
					this.SendPropertyChanged("ProjeAdı");
					this.OnProjeAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this.OnProjeBaşlangıçTarihiChanging(value);
					this.SendPropertyChanging();
					this._ProjeBaşlangıçTarihi = value;
					this.SendPropertyChanged("ProjeBaşlangıçTarihi");
					this.OnProjeBaşlangıçTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this.OnProjeBitişTarihiChanging(value);
					this.SendPropertyChanging();
					this._ProjeBitişTarihi = value;
					this.SendPropertyChanged("ProjeBitişTarihi");
					this.OnProjeBitişTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this.OnProjeDurumuChanging(value);
					this.SendPropertyChanging();
					this._ProjeDurumu = value;
					this.SendPropertyChanged("ProjeDurumu");
					this.OnProjeDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this.OnProjeGünChanging(value);
					this.SendPropertyChanging();
					this._ProjeGün = value;
					this.SendPropertyChanged("ProjeGün");
					this.OnProjeGünChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjeDetay")]
	public partial class ProjeDetay
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<int> _GörevSüresi;
		
		private System.Nullable<int> _IsciSayisi;
		
		private System.Nullable<System.DateTime> _GörevBaslangic;
		
		private System.Nullable<System.DateTime> _GorevBitis;
		
		private System.Nullable<int> _GörevDurumu;
		
		public ProjeDetay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevSüresi", DbType="Int")]
		public System.Nullable<int> GörevSüresi
		{
			get
			{
				return this._GörevSüresi;
			}
			set
			{
				if ((this._GörevSüresi != value))
				{
					this._GörevSüresi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciSayisi", DbType="Int")]
		public System.Nullable<int> IsciSayisi
		{
			get
			{
				return this._IsciSayisi;
			}
			set
			{
				if ((this._IsciSayisi != value))
				{
					this._IsciSayisi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaslangic", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaslangic
		{
			get
			{
				return this._GörevBaslangic;
			}
			set
			{
				if ((this._GörevBaslangic != value))
				{
					this._GörevBaslangic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorevBitis", DbType="Date")]
		public System.Nullable<System.DateTime> GorevBitis
		{
			get
			{
				return this._GorevBitis;
			}
			set
			{
				if ((this._GorevBitis != value))
				{
					this._GorevBitis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevDurumu", DbType="Int")]
		public System.Nullable<int> GörevDurumu
		{
			get
			{
				return this._GörevDurumu;
			}
			set
			{
				if ((this._GörevDurumu != value))
				{
					this._GörevDurumu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjeDurumu")]
	public partial class ProjeDurumu
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _ProjeDurumu1;
		
		public ProjeDurumu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ProjeDurumu", Storage="_ProjeDurumu1", DbType="Int")]
		public System.Nullable<int> ProjeDurumu1
		{
			get
			{
				return this._ProjeDurumu1;
			}
			set
			{
				if ((this._ProjeDurumu1 != value))
				{
					this._ProjeDurumu1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjeGörevDağılımı")]
	public partial class ProjeGörevDağılımı
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _PersonelNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<System.DateTime> _GörevBaşlangıç;
		
		private System.Nullable<System.DateTime> _GörevBitiş;
		
		private System.Nullable<int> _Ücret;
		
		public ProjeGörevDağılımı()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int")]
		public System.Nullable<int> PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaşlangıç", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaşlangıç
		{
			get
			{
				return this._GörevBaşlangıç;
			}
			set
			{
				if ((this._GörevBaşlangıç != value))
				{
					this._GörevBaşlangıç = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBitiş", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBitiş
		{
			get
			{
				return this._GörevBitiş;
			}
			set
			{
				if ((this._GörevBitiş != value))
				{
					this._GörevBitiş = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjeUstaAtaması")]
	public partial class ProjeUstaAtaması
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _PersonelNumarası;
		
		private System.Nullable<int> _ÇalışmaGünü;
		
		private System.Nullable<int> _ToplamÜcret;
		
		public ProjeUstaAtaması()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int")]
		public System.Nullable<int> PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÇalışmaGünü", DbType="Int")]
		public System.Nullable<int> ÇalışmaGünü
		{
			get
			{
				return this._ÇalışmaGünü;
			}
			set
			{
				if ((this._ÇalışmaGünü != value))
				{
					this._ÇalışmaGünü = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToplamÜcret", DbType="Int")]
		public System.Nullable<int> ToplamÜcret
		{
			get
			{
				return this._ToplamÜcret;
			}
			set
			{
				if ((this._ToplamÜcret != value))
				{
					this._ToplamÜcret = value;
				}
			}
		}
	}
	
	public partial class ÜcretlendirmeDataResult
	{
		
		private int _ÜcretNumarasi;
		
		private string _İşçiStatü;
		
		private System.Nullable<int> _Ücret;
		
		public ÜcretlendirmeDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜcretNumarasi", DbType="Int NOT NULL")]
		public int ÜcretNumarasi
		{
			get
			{
				return this._ÜcretNumarasi;
			}
			set
			{
				if ((this._ÜcretNumarasi != value))
				{
					this._ÜcretNumarasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşçiStatü", DbType="NVarChar(250)")]
		public string İşçiStatü
		{
			get
			{
				return this._İşçiStatü;
			}
			set
			{
				if ((this._İşçiStatü != value))
				{
					this._İşçiStatü = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
	
	public partial class SP_AtanacakProjeResult
	{
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
		public SP_AtanacakProjeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL")]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this._ProjeAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this._ProjeBaşlangıçTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this._ProjeBitişTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this._ProjeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this._ProjeGün = value;
				}
			}
		}
	}
	
	public partial class SP_EnDüşükTarihResult
	{
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
		public SP_EnDüşükTarihResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL")]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this._ProjeAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this._ProjeBaşlangıçTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this._ProjeBitişTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this._ProjeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this._ProjeGün = value;
				}
			}
		}
	}
	
	public partial class SP_EnYüksekTarihResult
	{
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
		public SP_EnYüksekTarihResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL")]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this._ProjeAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this._ProjeBaşlangıçTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this._ProjeBitişTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this._ProjeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this._ProjeGün = value;
				}
			}
		}
	}
	
	public partial class SP_GörevDağılımıGetirResult
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _PersonelNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<System.DateTime> _GörevBaşlangıç;
		
		private System.Nullable<System.DateTime> _GörevBitiş;
		
		private System.Nullable<int> _Ücret;
		
		public SP_GörevDağılımıGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int")]
		public System.Nullable<int> PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaşlangıç", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaşlangıç
		{
			get
			{
				return this._GörevBaşlangıç;
			}
			set
			{
				if ((this._GörevBaşlangıç != value))
				{
					this._GörevBaşlangıç = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBitiş", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBitiş
		{
			get
			{
				return this._GörevBitiş;
			}
			set
			{
				if ((this._GörevBitiş != value))
				{
					this._GörevBitiş = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
	
	public partial class SP_GörevDağılımıProjeBazlıTümVeriResult
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _PersonelNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<System.DateTime> _GörevBaşlangıç;
		
		private System.Nullable<System.DateTime> _GörevBitiş;
		
		private System.Nullable<int> _Ücret;
		
		public SP_GörevDağılımıProjeBazlıTümVeriResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int")]
		public System.Nullable<int> PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaşlangıç", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaşlangıç
		{
			get
			{
				return this._GörevBaşlangıç;
			}
			set
			{
				if ((this._GörevBaşlangıç != value))
				{
					this._GörevBaşlangıç = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBitiş", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBitiş
		{
			get
			{
				return this._GörevBitiş;
			}
			set
			{
				if ((this._GörevBitiş != value))
				{
					this._GörevBitiş = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
	
	public partial class SP_ProjeDetayDataResult
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<int> _GörevSüresi;
		
		private System.Nullable<int> _IsciSayisi;
		
		private System.Nullable<System.DateTime> _GörevBaslangic;
		
		private System.Nullable<System.DateTime> _GorevBitis;
		
		private System.Nullable<int> _GörevDurumu;
		
		public SP_ProjeDetayDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevSüresi", DbType="Int")]
		public System.Nullable<int> GörevSüresi
		{
			get
			{
				return this._GörevSüresi;
			}
			set
			{
				if ((this._GörevSüresi != value))
				{
					this._GörevSüresi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciSayisi", DbType="Int")]
		public System.Nullable<int> IsciSayisi
		{
			get
			{
				return this._IsciSayisi;
			}
			set
			{
				if ((this._IsciSayisi != value))
				{
					this._IsciSayisi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaslangic", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaslangic
		{
			get
			{
				return this._GörevBaslangic;
			}
			set
			{
				if ((this._GörevBaslangic != value))
				{
					this._GörevBaslangic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorevBitis", DbType="Date")]
		public System.Nullable<System.DateTime> GorevBitis
		{
			get
			{
				return this._GorevBitis;
			}
			set
			{
				if ((this._GorevBitis != value))
				{
					this._GorevBitis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevDurumu", DbType="Int")]
		public System.Nullable<int> GörevDurumu
		{
			get
			{
				return this._GörevDurumu;
			}
			set
			{
				if ((this._GörevDurumu != value))
				{
					this._GörevDurumu = value;
				}
			}
		}
	}
	
	public partial class SP_ÜcretlendirmeDataResult
	{
		
		private int _ÜcretNumarasi;
		
		private string _İşçiStatü;
		
		private System.Nullable<int> _Ücret;
		
		public SP_ÜcretlendirmeDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜcretNumarasi", DbType="Int NOT NULL")]
		public int ÜcretNumarasi
		{
			get
			{
				return this._ÜcretNumarasi;
			}
			set
			{
				if ((this._ÜcretNumarasi != value))
				{
					this._ÜcretNumarasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşçiStatü", DbType="NVarChar(250)")]
		public string İşçiStatü
		{
			get
			{
				return this._İşçiStatü;
			}
			set
			{
				if ((this._İşçiStatü != value))
				{
					this._İşçiStatü = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
	
	public partial class SP_YetenekDataResult
	{
		
		private int _YetenekNumarasi;
		
		private string _YetenekAdi;
		
		public SP_YetenekDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetenekNumarasi", DbType="Int NOT NULL")]
		public int YetenekNumarasi
		{
			get
			{
				return this._YetenekNumarasi;
			}
			set
			{
				if ((this._YetenekNumarasi != value))
				{
					this._YetenekNumarasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetenekAdi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string YetenekAdi
		{
			get
			{
				return this._YetenekAdi;
			}
			set
			{
				if ((this._YetenekAdi != value))
				{
					this._YetenekAdi = value;
				}
			}
		}
	}
	
	public partial class SP_PersonelYetenekGetirResult
	{
		
		private System.Nullable<int> _YetenekNumarasi;
		
		public SP_PersonelYetenekGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetenekNumarasi", DbType="Int")]
		public System.Nullable<int> YetenekNumarasi
		{
			get
			{
				return this._YetenekNumarasi;
			}
			set
			{
				if ((this._YetenekNumarasi != value))
				{
					this._YetenekNumarasi = value;
				}
			}
		}
	}
	
	public partial class SP_PersonelBilgisiResult
	{
		
		private int _PersonelNumarası;
		
		private string _Adi;
		
		private string _Soyadi;
		
		private string _İşçiStatü;
		
		private System.Nullable<int> _Ücret;
		
		private System.Nullable<int> _Durum;
		
		private System.Nullable<double> _YorgunlukPayi;
		
		public SP_PersonelBilgisiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int NOT NULL")]
		public int PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this._Adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this._Soyadi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşçiStatü", DbType="NVarChar(250)")]
		public string İşçiStatü
		{
			get
			{
				return this._İşçiStatü;
			}
			set
			{
				if ((this._İşçiStatü != value))
				{
					this._İşçiStatü = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="Int")]
		public System.Nullable<int> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this._Durum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorgunlukPayi", DbType="Float")]
		public System.Nullable<double> YorgunlukPayi
		{
			get
			{
				return this._YorgunlukPayi;
			}
			set
			{
				if ((this._YorgunlukPayi != value))
				{
					this._YorgunlukPayi = value;
				}
			}
		}
	}
	
	public partial class SP_ÜcretBilgisiGetirResult
	{
		
		private int _ÜcretNumarasi;
		
		private string _İşçiStatü;
		
		private System.Nullable<int> _Ücret;
		
		public SP_ÜcretBilgisiGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜcretNumarasi", DbType="Int NOT NULL")]
		public int ÜcretNumarasi
		{
			get
			{
				return this._ÜcretNumarasi;
			}
			set
			{
				if ((this._ÜcretNumarasi != value))
				{
					this._ÜcretNumarasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşçiStatü", DbType="NVarChar(250)")]
		public string İşçiStatü
		{
			get
			{
				return this._İşçiStatü;
			}
			set
			{
				if ((this._İşçiStatü != value))
				{
					this._İşçiStatü = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
	
	public partial class SP_ProjeBilgiGetirResult
	{
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
		public SP_ProjeBilgiGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL")]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this._ProjeAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this._ProjeBaşlangıçTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this._ProjeBitişTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this._ProjeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this._ProjeGün = value;
				}
			}
		}
	}
	
	public partial class SP_ProjeBilgiŞartResult
	{
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
		public SP_ProjeBilgiŞartResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL")]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this._ProjeAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this._ProjeBaşlangıçTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this._ProjeBitişTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this._ProjeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this._ProjeGün = value;
				}
			}
		}
	}
	
	public partial class SP_AtanacakGörevlerResult
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<int> _GörevSüresi;
		
		private System.Nullable<int> _IsciSayisi;
		
		private System.Nullable<System.DateTime> _GörevBaslangic;
		
		private System.Nullable<System.DateTime> _GorevBitis;
		
		private System.Nullable<int> _GörevDurumu;
		
		public SP_AtanacakGörevlerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevSüresi", DbType="Int")]
		public System.Nullable<int> GörevSüresi
		{
			get
			{
				return this._GörevSüresi;
			}
			set
			{
				if ((this._GörevSüresi != value))
				{
					this._GörevSüresi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciSayisi", DbType="Int")]
		public System.Nullable<int> IsciSayisi
		{
			get
			{
				return this._IsciSayisi;
			}
			set
			{
				if ((this._IsciSayisi != value))
				{
					this._IsciSayisi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaslangic", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaslangic
		{
			get
			{
				return this._GörevBaslangic;
			}
			set
			{
				if ((this._GörevBaslangic != value))
				{
					this._GörevBaslangic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorevBitis", DbType="Date")]
		public System.Nullable<System.DateTime> GorevBitis
		{
			get
			{
				return this._GorevBitis;
			}
			set
			{
				if ((this._GorevBitis != value))
				{
					this._GorevBitis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevDurumu", DbType="Int")]
		public System.Nullable<int> GörevDurumu
		{
			get
			{
				return this._GörevDurumu;
			}
			set
			{
				if ((this._GörevDurumu != value))
				{
					this._GörevDurumu = value;
				}
			}
		}
	}
	
	public partial class SP_AtanacakProjeGünResult
	{
		
		private int _ProjeNumarası;
		
		private string _ProjeAdı;
		
		private System.DateTime _ProjeBaşlangıçTarihi;
		
		private System.DateTime _ProjeBitişTarihi;
		
		private System.Nullable<int> _ProjeDurumu;
		
		private System.Nullable<int> _ProjeGün;
		
		public SP_AtanacakProjeGünResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int NOT NULL")]
		public int ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeAdı", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ProjeAdı
		{
			get
			{
				return this._ProjeAdı;
			}
			set
			{
				if ((this._ProjeAdı != value))
				{
					this._ProjeAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBaşlangıçTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBaşlangıçTarihi
		{
			get
			{
				return this._ProjeBaşlangıçTarihi;
			}
			set
			{
				if ((this._ProjeBaşlangıçTarihi != value))
				{
					this._ProjeBaşlangıçTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime ProjeBitişTarihi
		{
			get
			{
				return this._ProjeBitişTarihi;
			}
			set
			{
				if ((this._ProjeBitişTarihi != value))
				{
					this._ProjeBitişTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeDurumu", DbType="Int")]
		public System.Nullable<int> ProjeDurumu
		{
			get
			{
				return this._ProjeDurumu;
			}
			set
			{
				if ((this._ProjeDurumu != value))
				{
					this._ProjeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeGün", DbType="Int")]
		public System.Nullable<int> ProjeGün
		{
			get
			{
				return this._ProjeGün;
			}
			set
			{
				if ((this._ProjeGün != value))
				{
					this._ProjeGün = value;
				}
			}
		}
	}
	
	public partial class SP_ProjeUstaGösterResult
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _PersonelNumarası;
		
		private System.Nullable<int> _ÇalışmaGünü;
		
		private System.Nullable<int> _ToplamÜcret;
		
		public SP_ProjeUstaGösterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int")]
		public System.Nullable<int> PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÇalışmaGünü", DbType="Int")]
		public System.Nullable<int> ÇalışmaGünü
		{
			get
			{
				return this._ÇalışmaGünü;
			}
			set
			{
				if ((this._ÇalışmaGünü != value))
				{
					this._ÇalışmaGünü = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToplamÜcret", DbType="Int")]
		public System.Nullable<int> ToplamÜcret
		{
			get
			{
				return this._ToplamÜcret;
			}
			set
			{
				if ((this._ToplamÜcret != value))
				{
					this._ToplamÜcret = value;
				}
			}
		}
	}
	
	public partial class SP_MüsaitFirmaİşçisiResult
	{
		
		private int _PersonelNumarası;
		
		private System.Nullable<double> _YorgunlukPayi;
		
		public SP_MüsaitFirmaİşçisiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int NOT NULL")]
		public int PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorgunlukPayi", DbType="Float")]
		public System.Nullable<double> YorgunlukPayi
		{
			get
			{
				return this._YorgunlukPayi;
			}
			set
			{
				if ((this._YorgunlukPayi != value))
				{
					this._YorgunlukPayi = value;
				}
			}
		}
	}
	
	public partial class SP_MüsaitFirmaUstalarıResult
	{
		
		private int _PersonelNumarası;
		
		public SP_MüsaitFirmaUstalarıResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int NOT NULL")]
		public int PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
	}
	
	public partial class SP_MüsaitTaşeronİşçisiResult
	{
		
		private int _PersonelNumarası;
		
		private System.Nullable<double> _YorgunlukPayi;
		
		public SP_MüsaitTaşeronİşçisiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int NOT NULL")]
		public int PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorgunlukPayi", DbType="Float")]
		public System.Nullable<double> YorgunlukPayi
		{
			get
			{
				return this._YorgunlukPayi;
			}
			set
			{
				if ((this._YorgunlukPayi != value))
				{
					this._YorgunlukPayi = value;
				}
			}
		}
	}
	
	public partial class SP_MüsaitTaşeronUstalarıResult
	{
		
		private int _PersonelNumarası;
		
		public SP_MüsaitTaşeronUstalarıResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int NOT NULL")]
		public int PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
	}
	
	public partial class SP_PersonelDurumuXResult
	{
		
		private System.Nullable<int> _ProjeNumarası;
		
		private System.Nullable<int> _PersonelNumarası;
		
		private System.Nullable<int> _Görevİsmi;
		
		private System.Nullable<System.DateTime> _GörevBaşlangıç;
		
		private System.Nullable<System.DateTime> _GörevBitiş;
		
		private System.Nullable<int> _Ücret;
		
		public SP_PersonelDurumuXResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjeNumarası", DbType="Int")]
		public System.Nullable<int> ProjeNumarası
		{
			get
			{
				return this._ProjeNumarası;
			}
			set
			{
				if ((this._ProjeNumarası != value))
				{
					this._ProjeNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelNumarası", DbType="Int")]
		public System.Nullable<int> PersonelNumarası
		{
			get
			{
				return this._PersonelNumarası;
			}
			set
			{
				if ((this._PersonelNumarası != value))
				{
					this._PersonelNumarası = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Görevİsmi", DbType="Int")]
		public System.Nullable<int> Görevİsmi
		{
			get
			{
				return this._Görevİsmi;
			}
			set
			{
				if ((this._Görevİsmi != value))
				{
					this._Görevİsmi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBaşlangıç", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBaşlangıç
		{
			get
			{
				return this._GörevBaşlangıç;
			}
			set
			{
				if ((this._GörevBaşlangıç != value))
				{
					this._GörevBaşlangıç = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GörevBitiş", DbType="Date")]
		public System.Nullable<System.DateTime> GörevBitiş
		{
			get
			{
				return this._GörevBitiş;
			}
			set
			{
				if ((this._GörevBitiş != value))
				{
					this._GörevBitiş = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ücret", DbType="Int")]
		public System.Nullable<int> Ücret
		{
			get
			{
				return this._Ücret;
			}
			set
			{
				if ((this._Ücret != value))
				{
					this._Ücret = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
